### ISSUE TITLE
Product Show > Product Section Checklist

### ISSUE THREAD

**Issue by drafter01** [drafter01/study-with-Kimbug#1]
## Checklist

- Tab + TabPanel 구조
- [ ] `role` 을 사용해서 유기적으로 연결관계 구축
- 공통컴포넌트
- [ ] TabPanel 내 헤더영역
  - [x] 텍스트 only
  - [x] 텍스트 + 뱃지 + 아이콘링크
  - [x] 텍스트 + 뱃지 + 텍스트링크
  - [x] 텍스트 + 뱃지 + 아이콘 버트 (드랍다운 스타일, 모바일 only)
- [ ] TabPanel 내 Table
